name: gwcluster
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gwpy=2.1.3
  - matplotlib=3.3.2
  - numpy=1.21.2
  - pip=21.2.4
  - pip:
    - WunderWeather
  - pyyaml=6.0
  - scikit-learn=1.0.2
  - typer=0.6.1
  - jinja2=3.0.3
  - corner=2.2.1
